language: php

matrix:
  include:
    - php: 5.5
      env: oauth=oauth-1.2.3 COMPOSER_OPTS=""
    - php: 5.5
      env: oauth=oauth-1.2.3 COMPOSER_OPTS="--prefer-lowest"
    - php: 5.6
      env: oauth=oauth-1.2.3 COMPOSER_OPTS=""
    - php: 5.6
      env: oauth=oauth-1.2.3 COMPOSER_OPTS="--prefer-lowest"
    - php: 7.0
      env: oauth=oauth COMPOSER_OPTS=""
    - php: 7.0
      env: oauth=oauth COMPOSER_OPTS="--prefer-lowest"
    - php: 7.1
      env: oauth=oauth COMPOSER_OPTS=""
    - php: 7.1
      env: oauth=oauth COMPOSER_OPTS="--prefer-lowest"
    - php: 7.2
      env: oauth=oauth COMPOSER_OPTS=""
    - php: 7.2
      env: oauth=oauth COMPOSER_OPTS="--prefer-lowest"
    - php: nightly
      env: oauth=oauth COMPOSER_OPTS=""
    - php: nightly
      env: oauth=oauth COMPOSER_OPTS="--prefer-lowest"
  allow_failures:
    - php: nightly

install:
  - pecl install $oauth
  - composer self-update --snapshot
  - composer update $COMPOSER_OPTS

script:
  - vendor/bin/phpunit --coverage-clover=clover.xml
  - tests/lint.sh

after_success:
  - vendor/bin/coveralls

git:
  depth: 5

dist: trusty
sudo: false
