language: php

matrix:
  include:
    - php: 5.5
      env: oauth=oauth-1.2.3 COMPOSER_OPTS=""
    - php: 5.5
      env: oauth=oauth-1.2.3 COMPOSER_OPTS="--prefer-lowest"
    - php: 5.6
      env: oauth=oauth-1.2.3 COMPOSER_OPTS=""
    - php: 5.6
      env: oauth=oauth-1.2.3 COMPOSER_OPTS="--prefer-lowest"
    - php: 7.0
      env: oauth=oauth COMPOSER_OPTS=""
    - php: 7.0
      env: oauth=oauth COMPOSER_OPTS="--prefer-lowest"

install:
  - pecl install $oauth
  - composer self-update
  - composer update $COMPOSER_OPTS

script:
  - phpunit tests
  - ./tests/lint.sh

git:
  depth: 5
